# generate-config.ps1
# Reads .env and writes config.js for local development.
# Run this after cloning or updating .env.
# In production, config.js is generated by Cloud Build from GCP Secret Manager.

$envFile = Join-Path $PSScriptRoot ".env"
if (-not (Test-Path $envFile)) {
  Write-Error ".env file not found. Copy .env.example to .env and fill in the values."
  exit 1
}

$cfg = @{}
foreach ($line in Get-Content $envFile) {
  if ($line -match '^\s*([^#=\s]+)\s*=\s*(.+)\s*$') {
    $cfg[$matches[1]] = $matches[2].Trim()
  }
}

$content = "// AUTO-GENERATED -- do not commit (listed in .gitignore).`n"
$content += "// Local:      run generate-config.ps1 to regenerate from .env`n"
$content += "// Production: generated by Cloud Build from GCP Secret Manager`n"
$content += "window.DRIVETRACKER_CONFIG = {`n"
$content += "  FIREBASE_API_KEY:             '" + $cfg['FIREBASE_API_KEY'] + "',`n"
$content += "  FIREBASE_AUTH_DOMAIN:         '" + $cfg['FIREBASE_AUTH_DOMAIN'] + "',`n"
$content += "  FIREBASE_PROJECT_ID:          '" + $cfg['FIREBASE_PROJECT_ID'] + "',`n"
$content += "  FIREBASE_STORAGE_BUCKET:      '" + $cfg['FIREBASE_STORAGE_BUCKET'] + "',`n"
$content += "  FIREBASE_MESSAGING_SENDER_ID: '" + $cfg['FIREBASE_MESSAGING_SENDER_ID'] + "',`n"
$content += "  FIREBASE_APP_ID:              '" + $cfg['FIREBASE_APP_ID'] + "',`n"
$content += "  ALLOWED_EMAIL:                '" + $cfg['ALLOWED_EMAIL'] + "',`n"
$content += "};"

$content | Out-File -FilePath (Join-Path $PSScriptRoot "config.js") -Encoding utf8 -NoNewline
Write-Host "config.js generated from .env"
